image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

stages:
  - release
  - deploy

build_image:
  stage: release
  tags:
    - wavesenterprise
  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${REGISTRY}"
    # Pull latest image for using cache
    - docker pull "${REGISTRY}/vostok/east-client:latest" || true
    # Add file versions.json
    - 'echo "{\"BUILD_ID\": ${CI_JOB_ID}, \"GIT_COMMIT\": \"${CI_COMMIT_SHA}\", \"DOCKER_TAG\": \"${CI_COMMIT_REF_NAME}\"}" > versions.json'
    - docker build --cache-from "${REGISTRY}/vostok/east-client:latest" -t "${REGISTRY}/vostok/east-client:${CI_COMMIT_REF_NAME}" -t "${REGISTRY}/vostok/east-client:latest" -f Dockerfile .
    - docker push "${REGISTRY}/vostok/east-client:${CI_COMMIT_REF_NAME}"
    - docker push "${REGISTRY}/vostok/east-client:latest"
  only:
    - branches
    - tags
